/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package jdbc.program;

import java.util.List;
import javax.swing.DefaultListModel;
import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;

/**
 *
 * @author Jati
 */
public class JframeUtama extends javax.swing.JFrame {
    
    /** Creates new form JframeUtama */
    
    DefaultListModel<Integer> idModel = new DefaultListModel<>();
    DefaultListModel<String> NamaModel = new DefaultListModel<>();
    MysqlMahasiswaService service = new MysqlMahasiswaService();
    public JframeUtama() {
        initComponents();
        
    }
    
    public void updateList(){
        jList_ID.setModel(idModel);
        jList_Nama.setModel(NamaModel);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_ID = new javax.swing.JLabel();
        jLabel_Nama = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_ID = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_Nama = new javax.swing.JList<>();
        jButton_AllData = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Nama1 = new javax.swing.JTextField();
        jTextField_ID1 = new javax.swing.JTextField();
        jButton_ADD = new javax.swing.JButton();
        jTextField_ID2 = new javax.swing.JTextField();
        jTextField_Nama2 = new javax.swing.JTextField();
        jTextField_Nama3 = new javax.swing.JTextField();
        jButton_Edit = new javax.swing.JButton();
        jButton_Hapus = new javax.swing.JButton();
        jButton_ResetIndeks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_ID.setText("ID");

        jLabel_Nama.setText("NAMA");

        jList_ID.setModel(new javax.swing.AbstractListModel<Integer>() {
            Integer[] integers = { 1, 2, 3, 4, 5 };
            public int getSize() { return integers.length; }
            public Integer getElementAt(int i) { return integers[i]; }
        });
        jList_ID.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_IDValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList_ID);
        jList_ID.getAccessibleContext().setAccessibleParent(jList_ID);

        jList_Nama.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList_Nama);

        jButton_AllData.setText("Ambil Semua Data");
        jButton_AllData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AllDataActionPerformed(evt);
            }
        });

        jLabel1.setText("nama :");

        jButton_ADD.setText("Tambahkan");
        jButton_ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ADDActionPerformed(evt);
            }
        });

        jButton_Edit.setText("Edit");
        jButton_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditActionPerformed(evt);
            }
        });

        jButton_Hapus.setText("Hapus");
        jButton_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HapusActionPerformed(evt);
            }
        });

        jButton_ResetIndeks.setText("Reset Indeks");
        jButton_ResetIndeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetIndeksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Nama)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_AllData, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_Nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Nama2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Edit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_ID2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Nama3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Hapus))
                            .addComponent(jButton_ResetIndeks))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ID)
                    .addComponent(jLabel_Nama))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton_AllData)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Nama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jButton_ADD)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Nama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Edit))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Nama3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Hapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jButton_ResetIndeks)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AllDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AllDataActionPerformed
        // TODO add your handling code here:
        List<Mahasiswa> listMhs = service.getAll();
        
        idModel.clear();
        NamaModel.clear();
        for (Mahasiswa mhs : listMhs){
            idModel.addElement(mhs.getId());
            NamaModel.addElement(mhs.getNama());
        }
        updateList();
    }//GEN-LAST:event_jButton_AllDataActionPerformed

    private void jButton_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditActionPerformed
        // TODO add your handling code here:
        if (jTextField_ID1.getText().isEmpty()|| jTextField_Nama2.getText().isEmpty()){
            return;
        }
        try{
            int id = Integer.parseInt(jTextField_ID1.getText());
            String nama = jTextField_Nama2.getText();
            Mahasiswa mhs = service.makeMhsObject();
            mhs.setId(id);
            mhs.setNama(nama);
            service.update(mhs);
            idModel.clear();
            NamaModel.clear();
            List<Mahasiswa> listMhs = service.getAll();
            for (Mahasiswa mahasiswa : listMhs) {
                idModel.addElement(mahasiswa.getId());
                NamaModel.addElement(mahasiswa.getNama());
            }
            updateList();
        } catch (NumberFormatException e) {
            System.out.println("Invalid ID: " + e.getMessage());
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton_EditActionPerformed

    private void jButton_ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ADDActionPerformed
        // TODO add your handling code here:
        try {
            // Mengambil nama dari form
            String nama = jTextField_Nama1.getText();
            if (nama.isEmpty() || nama.trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Mendapatkan ID berikutnya yang tersedia (berurutan dari 1)
            int nextId = service.getNextId();
            
            // Membuat objek mahasiswa baru
            Mahasiswa mhs = new Mahasiswa(nextId, nama);
            service.add(mhs);
            idModel.clear();
            NamaModel.clear();
            List<Mahasiswa> listMhs = service.getAll();
            for (Mahasiswa mahasiswa : listMhs) {
                idModel.addElement(mahasiswa.getId());
                NamaModel.addElement(mahasiswa.getNama());
            }
            updateList();
        } catch (Exception e) {
            System.out.println("Error adding student: " + e.getMessage());
        }
        jTextField_Nama1.setText("");
    }//GEN-LAST:event_jButton_ADDActionPerformed

    private void jButton_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HapusActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jTextField_ID2.getText());
            service.delete(id);
            jButton_AllDataActionPerformed(evt);
            List<Mahasiswa> listMhs = service.getAll();
            for (Mahasiswa mhs : listMhs) {
                idModel.addElement(mhs.getId());
                NamaModel.addElement(mhs.getNama());
            }
            updateList();
        } catch (NumberFormatException e) {
            System.out.println("Invalid ID format: " + e.getMessage());
        } catch (Exception e) {
            System.out.println("Error deleting student: " + e.getMessage());
        }
        jTextField_ID1.setText("");
        jTextField_Nama2.setText("");
        jTextField_ID2.setText("");
        jTextField_Nama3.setText("");
    }//GEN-LAST:event_jButton_HapusActionPerformed

    private void jButton_ResetIndeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetIndeksActionPerformed
        // TODO: handle exception
        try {
            idModel.clear();
            NamaModel.clear();
            updateList();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error Reset Indeks: "+ e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        jTextField_ID1.setText("");
        jTextField_Nama2.setText("");
        jTextField_ID2.setText("");
        jTextField_Nama3.setText("");

    }//GEN-LAST:event_jButton_ResetIndeksActionPerformed

    private void jList_IDValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_IDValueChanged
        // TODO add your handling code here:
        try {
            if (!evt.getValueIsAdjusting() && jList_ID.getSelectedValue() != null) {
                int selectedId = jList_ID.getSelectedValue();
                int indeks = idModel.indexOf(selectedId);
                String selectedName = NamaModel.getElementAt(indeks);
                jTextField_ID1.setText(String.valueOf(selectedId));
                jTextField_Nama2.setText(selectedName);
                jTextField_ID2.setText(String.valueOf(selectedId));
                jTextField_Nama3.setText(selectedName);}
        } catch (Exception e) {
            // TODO: handle exception
        }
    }//GEN-LAST:event_jList_IDValueChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ADD;
    private javax.swing.JButton jButton_AllData;
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JButton jButton_Hapus;
    private javax.swing.JButton jButton_ResetIndeks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_Nama;
    private javax.swing.JList<Integer> jList_ID;
    private javax.swing.JList<String> jList_Nama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField_ID1;
    private javax.swing.JTextField jTextField_ID2;
    private javax.swing.JTextField jTextField_Nama1;
    private javax.swing.JTextField jTextField_Nama2;
    private javax.swing.JTextField jTextField_Nama3;
    // End of variables declaration//GEN-END:variables

}
